version: '3'
services:
  my-app:
    container_name: node_my-app_1
    image: krnmalde/final
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - mongo-net2
  mongodb:
    image: mongo:4
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-net2
  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mongo-net2
volumes:
  mongo-data:
    driver: local

networks:
  mongo-net2:
    driver: bridge